export default {
  // Action
  ADD_LOCATION_OPEN: 'ADD_LOCATION_OPEN',
  UPDATE_ADD_LOCATION_STATE: 'UPDATE_ADD_LOCATION_STATE',
  ADD_POKEMON: 'ADD_POKEMON',
  ADD_GYM: 'ADD_GYM',
  ADD_POKESTOP: 'ADD_POKESTOP',
  ADD_LOCATION_LATLNG: 'ADD_LOCATION_LATLNG',
  ADD_LOCATION_CLOSE: 'ADD_LOCATION_CLOSE',

  // State
  ADD_LOCATION_START: 'ADD_LOCATION_START',
  ADD_LOCATION_POKEMON_SELECT: 'ADD_LOCATION_POKEMON_SELECT',
  ADD_LOCATION_POKEMON_CONFIRM: 'ADD_LOCATION_POKEMON_CONFIRM',
  ADD_LOCATION_HOW: 'ADD_LOCATION_HOW',
  ADD_LOCATION_HERE: 'ADD_LOCATION_HERE',
  ADD_LOCATION_TO_MAP: 'ADD_LOCATION_TO_MAP',
  ADD_LOCATION_GYM: 'ADD_LOCATION_GYM',
  ADD_LOCATION_POKESTOP: 'ADD_LOCATION_POKESTOP',
  ADD_LOCATION_SUBMIT: 'ADD_LOCATION_SUBMIT',
}