export default {
  // Action
  ADD_LOCATION_TOGGLE: 'ADD_LOCATION_TOGGLE',
  INITIALIZE_ADD: 'INITIALIZE_ADD',
  ADD_POKEMON: 'ADD_POKEMON',
  ADD_GYM: 'ADD_GYM',
  ADD_POKESTOP: 'ADD_POKESTOP',
  ADD_LOCATION_LATLNG: 'ADD_LOCATION_LATLNG',
  ADD_LOCATION_RESET: 'ADD_LOCATION_RESET',

  // State
  ADD_LOCATION_POKEMON: 'ADD_LOCATION_POKEMON',
  ADD_LOCATION_GYM: 'ADD_LOCATION_GYM',
  ADD_LOCATION_POKESTOP: 'ADD_LOCATION_POKESTOP'
}