
export default {
  // Actions
  AUTH_OPEN: 'AUTH_OPEN',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_FACEBOOK_PROVIDER: 'AUTH_FACEBOOK_PROVIDER',
  AUTH_GOOGLE_PROVIDER: 'AUTH_GOOGLE_PROVIDER',
  AUTH_TWITTER_PROVIDER: 'AUTH_TWITTER_PROVIDER',

  // States
  AUTH_ANONYMOUS: 'AUTH_ANONYMOUS',
  AUTH_AWAITING_RESPONSE: 'AUTH_AWAITING_RESPONSE',
  AUTH_LOGGED_IN: 'AUTH_LOGGED_IN',

  // Variables
  AUTH_GUEST_USERNAME: 'guest',
  
};
