export default {
  // Actions
  SET_SEARCH_TERM: 'SET_SEARCH_TERM',
  SET_SEARCH_RADIUS: 'SET_SEARCH_RADIUS',
  SET_SEARCH_BY: 'SET_SEARCH_BY',
  SET_SEARCH: 'SET_SEARCH',
  SET_SEARCH_FILTERS: 'SET_SEARCH_FILTERS',

  // State
  SEARCH_BY_POKEMON: 'SEARCH_BY_POKEMON',
  SEARCH_BY_LOCATION: 'SEARCH_BY_LOCATION',
  SEARCH_BY_PIN: 'SEARCH_BY_PIN',

  // Allowable Radius
  RADIUS_SMALL: 10,
  RADIUS_MEDIUM: 25,
  RADIUS_LARGE: 50,
}